---
stages:
  - build
  - git-sync

buster:
  stage: build
  variables:
    DEB_SUITE: buster
  script:
    - docker login -u="${QUAY_IO_USER}" -p="${QUAY_IO_PASSWORD}" quay.io
    - >-
      docker build
      --build-arg=DEB_SUITE=${DEB_SUITE}
      --force-rm=true
      --label=org.label-schema.build-date="$(date --utc --iso-8601=seconds)"
      --label=org.label-schema.vcs-ref="${CI_COMMIT_SHA}"
      --label=org.label-schema.vcs-url="${CI_PROJECT_URL}.git"
      --pull=true
      -t quay.io/${CI_PROJECT_PATH}:${DEB_SUITE}
      .
    - docker push quay.io/${CI_PROJECT_PATH}:${DEB_SUITE}
  only:
    - master
  except:
    - triggers
  tags:
    - docker-build

git-sync:
  script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 -d)
    - git sync-remote
        git@github.com:${CI_PROJECT_PATH}.git
        git@git.boo.tc:${CI_PROJECT_PATH}.git
  stage: git-sync
  image: dkr.boo.tc/bootc/github-gitlab-sync:latest
  only:
    - triggers

# vim: ai ts=2 sw=2 et sts=2 ft=yaml
