---
stages:
  - build
  - git-sync

buster:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  variables:
    DEB_SUITE: buster
  script:
    - export DKR_IMAGE="$(echo $CI_PROJECT_PATH | tr '[:upper:]' '[:lower:]')"
    - mkdir -p /root/.docker
    - echo "{\"auths\":{\"v1.quay.io\":{\"auth\":\"${QUAY_IO_AUTH}\"}}}" > /root/.docker/config.json
    - >-
      /kaniko/executor
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/Dockerfile
      --build-arg=DEB_SUITE=${DEB_SUITE}
      --build-arg=BUILD_DATE="$(date --utc +%Y-%m-%dT%H:%M:%SZ)"
      --build-arg=VCS_REF=${CI_COMMIT_SHA}
      --destination v1.quay.io/${DKR_IMAGE}:${DEB_SUITE}
  only:
    - master
  except:
    - triggers

git-sync:
  script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | base64 -d | ssh-add -
    - git sync-remote
        git@github.com:${CI_PROJECT_PATH}.git
        git@git.boo.tc:${CI_PROJECT_PATH}.git
  stage: git-sync
  image: quay.io/bootc/github-gitlab-sync:latest
  only:
    - triggers

# vim: ai ts=2 sw=2 et sts=2 ft=yaml
