---
stages:
  - build
  - git-sync

buster:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  variables:
    DEB_SUITE: buster
  script:
    - export DKR_IMAGE="$(echo $CI_PROJECT_PATH | tr '[:upper:]' '[:lower:]')"
    - \[ -z "$DOCKER_CONFIG" ] && export DOCKER_CONFIG=/kaniko/.docker
    - |
      cat > "${DOCKER_CONFIG}/config.json" <<EOF
      {
        "auths": {
          "https://index.docker.io/v1/": {
            "auth": "${DOCKER_HUB_AUTH}"
          },
          "${CI_REGISTRY}": {
            "username": "${CI_REGISTRY_USER}",
            "password": "${CI_REGISTRY_PASSWORD}"
          }
        }
      }
      EOF
    - >-
      /kaniko/executor
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/Dockerfile
      --reproducible
      --build-arg=DEB_SUITE=${DEB_SUITE}
      --build-arg=BUILD_DATE="$(date --utc +%Y-%m-%dT%H:%M:%SZ)"
      --build-arg=VCS_REF=${CI_COMMIT_SHA}
      --destination "${CI_REGISTRY_IMAGE}:${DEB_SUITE}"
      --destination "${DKR_IMAGE}:${DEB_SUITE}"
  only:
    - master
  except:
    - triggers

git-sync:
  script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | base64 -d | ssh-add -
    - git sync-remote
        git@github.com:${CI_PROJECT_PATH}.git
        git@git.boo.tc:${CI_PROJECT_PATH}.git
  stage: git-sync
  image: dkr.boo.tc/bootc/github-gitlab-sync:latest
  only:
    - triggers

# vim: ai ts=2 sw=2 et sts=2 ft=yaml
